local C, D = unpack(select(2,...))
local FONT, SOUND = D.MEDIA.FONT, D.MEDIA.SOUND
D.CFG = {
	['UPDATE']					= false,

	['UNITFRAME_MAJOR']			= {
		alpha					= 1,
		x					= 170,
		y					= -7.5,
		hpBarW				= 210,
		hpBarH				= 3,
		ppBarW				= 210,
		ppBarH				= 1,
		font					= UNIT_NAME_FONT,
		fontSize				= 13,
		fontSize_health			= 28,
		fontSize_power			= 8,
		fontSize_info			= 10,
		fontSize_class			= 10,
		fontFlag				= 'THINOUTLINE',
							  },
	['UNITFRAME_MINOR']			= {
		alpha					= 1,
		x					= 148,
		y					= 117,
		hpBarW				= 130,
		hpBarH				= 1,
		ppBarW				= 130,
		ppBarH				= 1,
		font					= UNIT_NAME_FONT,
		fontSize				= 10,
		fontSize_health			= 12,
		fontSize_power			= 8,
		fontFlag				= 'THINOUTLINE',
		frequency				= 0.1,					
							  },
	['AURA_MAJOR']				= {
		amount				= 20,
		alpha					= 1,
		size					= 16,
		gap					= 8,
		font					= FONT.pixel,
		fontSize_stack			= 20,
		fontSize_timer			= 10,
		fontFlag				= 'THINOUTLINE',
							  },
	['AURA_MINOR']				= {
		amount				= 10,
		alpha					= 1,
		size					= 16,
		gap					= 6,
		font					= FONT.pixel,
		fontSize_stack			= 20,
		fontSize_timer			= 10,
		fontFlag				= 'THINOUTLINE',
							  },
	['AURA_RAID']				= {
		amount				= 40,
		alpha					= 1,
		size					= 20,
		gap					= 10,
		font					= FONT.pixel,
		fontSize_stack			= 20,
		fontSize_timer			= 10,
		fontFlag				= 'THINOUTLINE',
							  },
	['COMBAT_EVENT']				= {
		x					= 60,
		y					= -8,
		font					= FONT.edo,
		fontSize				= 20,
		fontFlag				= 'THINOUTLINE',
		spellname_font			= DAMAGE_TEXT_FONT,
		spellname_fontSize		= 14,
		spellname_fontFlag		= 'THINOUTLINE',
		critsound				= SOUND.Excellent,
		hurtsound				= SOUND.Damn,
							  },
	['OTHERS']					= {
		MOUNTED_ALPHA			= .382,
		killBZBossFrame			= false,
		killBZRaidFrame			= false,
		killBZRuneFrame			= false,
							  },
}